* Measurement Helper
Simplistic web application to help doing repeated measurements. Designed to be hosted for free on [[https://www.heroku.com/][Heroku]]. UI texts are in Finnish, source code in English. Consider it *public domain*, no warranties provided.

- Password protected Web UI for logging/viewing data
- Email notifications with configurable alert intervals for different measurement types

Built with
- [[http://flask.pocoo.org/][Python Flask]] web framework
  - [[https://flask-login.readthedocs.org/][Flask-Login]] extension for simple single user authentication
  - [[http://jinja.pocoo.org/][Jinja2]] templating engine
  - [[http://getbootstrap.com/][Bootstrap]] HTML UI toolkit with [[https://github.com/mbr/flask-bootstrap][Flask-Bootstrap]] extension
  - [[https://wtforms.readthedocs.org/en/latest/][WTForms]] HTML form library for input validation
- [[https://dataset.readthedocs.org/][Python Dataset]] SQL Database wrapper (tested on SQLite and PostgreSQL)
- [[https://mailgun.com/][Mailgun]] for sending emails

** To Do
- [X] +User auth by env token, [[http://flask-sqlalchemy.pocoo.org/2.0/quickstart/][flask-login]]
- [X] [[https://dataset.readthedocs.org/en/latest/][Dataset]] and sqlite
- [X] Views
- [X] [[https://github.com/lepture/flask-wtf][WTForms]] classes & validation for entries
- [X] Schedule [[http://pythonhosted.org/Flask-Mail/][flask-mail]] notifications
- [X] Serving on heroku
- [ ] Backups
- [ ] SSL
- [ ] Secret token

Code was written in quickly in few days and was not tested by design. It wouldn't be convenient to build much bigger programs than this without automated testing facilities in place.
  
* Environment setup
Tested on Linux Mint 17.2 (Ubuntu 14.04) and OSX 10.10 (homebrew python3).
Using Heroku free plan for production. 

Distribution provided prerequirements:
- Python 3.4 with development package
- PostgreSQL development package libpq-dev
- [[https://en.wikipedia.org/wiki/Pip_(package_manager)][pip]] package manager
=sudo apt-get install python3-pip python3-dev libpq-dev=

Some (optional) tooling provided by pip:
- [[http://docs.python-guide.org/en/latest/dev/virtualenvs/][virtualenv]] Python project dependency isolation tool
- [[https://virtualenvwrapper.readthedocs.org/en/latest/][virtualenvwrapper]] virtualenv helper (supported by [[https://www.gnu.org/software/emacs/][Emacs]] [[https://github.com/jorgenschaefer/elpy/wiki][ELPY Python IDE]])
=pip install virtualenv virtualenvwrapper=
=mkvirtualenv -p /usr/bin/python3.4 measurement-helper=

=mkvirtualenv= command activates the created virtual environment by default. Later it can be activated with =workon koodilehto-intra= 

Install project dependencies =pip install -r requirements.txt=.

Pip may throw permission error about pip cache folder when installing. Fix by running =sudo chown -R <your username>:<your username> $HOME/.cache/pip= on Linux or =sudo chown -R <your username> $HOME/Library/Caches/pip= on OSX.

** Initializing database and environment variables
Initialize tables =python server.py init_db=.
Database can be cleared with command =python server.py drop_db= when necessary.

Application defaults to password 'topsecret' and throws errors when running email notification checker if following variables are not set:

#+BEGIN_SRC sh
FLASK_APP_PASSWORD="somethingHard_to-guess"
MAILGUN_KEY = 'key-xxxblablaetcxxx'
ADMIN_EMAIL="foo@example.com"
FLASK_APP_EMAIL="bar@example.com"
SERVER_ADDRESS = 'http://your-awesome-domain.net'
#+END_SRC

For Heroku, config variables are set with command =heroku config:set <VARIABLE_SETTING>=.
* Development server
Command =python server.py dev= defaults to localhost:5000. Changing host and port for exposing server for external requests (might be dangerous if debugger is enabled) can be accomplished by running =python server.py dev -h 0.0.0.0 -p 80=.
* Production server
** Heroku node setup
With [[https://toolbelt.heroku.com/][Heroku Toolbelt]] installed and account configured:

1) Clone repository =git clone <repository url>=
2) Create Heroku app =heroku create <application_name>=
3) Add free PostgeSQL addon =heroku addons:create heroku-postgresql:hobby-dev= 
4) Push local repository to Heroku =git push heroku master=
5) Initialize database =heroku run python app/server.py init_db=
6) Setup environment variables from previous step
7) Access application at =http://<application_name>.herokuapp.com=

When continuing work on deployed Heroku app on other machine etc, skip steps 2-3 and instead set remote to existing Heroku git repository =heroku git:remote -a <application_name>=.

Optionally setup cronjob somewhere to keep node running during daytime by adding following line to cron:

=*/8 06-21 * * * curl http://<app_name>.herokuapp.com=

** Running elsewhere
See Procfile (Heroku configuration file) for hints, at least logging won't work by default via run.py so it needs work.
** Setup notification scheduler
Notifications for doing scheduled measurements are sent to addresses declared by environment variables =ADMIN_EMAIL= and =FLASK_APP_EMAIL=. Database stores only date, so hourly running check_notifications script may send notifications during night, which might cause undesired side effects.
*** Heroku Scheduler
Heroku Scheduler can be used to send notifications on daily basis, but it *requires linking a credit card to Heroku account* as scheduled tasks going over the given 750 monthly free dyno hours will require payment. To enable notifications via Heroku Scheduler addon:

1) =heroku addons:create scheduler=
2) Open scheduler web UI =heroku addons:open scheduler=
3) Setup new scheduler command =python app/server.py check_notifications=
*** Calling Heroku node to run script via cron / anacron
1) Run =crontab -e= or edit =/etc/anacrontab=
2) Add rule =* 7 * * * heroku run --app <app_name> python app/server.py check_notifications=

(didn't test this yet, but should work, maybe with minor fixing)
*** Running script on other machine via cron / anacron
Notification script =python app/server.py check_notifications= can be scheduled simply in cron or anacron. Machine should have environment variable DATABASE_URL set to application database. Heroku database url can be queried with =heroku config=.
